# Generated by Django 3.1.5 on 2021-01-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210121_2131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplication',
            table=None,
        ),
    ]
