# Generated by Django 3.1.5 on 2021-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='exp_required',
            field=models.CharField(default='1+', max_length=10),
        ),
    ]
